include:
  local: templates/v6.yml

# custom target to make sure we use the install_julia.sh script from this branch
.julia:
  script:
    - |
      apt-get -qq update
      DEBIAN_FRONTEND=noninteractive apt-get -qqy -o=Dpkg::Use-Pty=0 install wget
      eval "$(bash install_julia.sh $JULIA)"

julia:1.0:
  extends: .julia
  variables:
    JULIA: '1.0'

julia:nightly:
  extends: .julia
  variables:
    JULIA: nightly

julia:source:
  extends: .julia
  variables:
    JULIA: source

# same, but with the addition of setting-up a package like GitLab normally does
.example:
  before_script:
    - |
      apt -qq update
      DEBIAN_FRONTEND=noninteractive apt-get -qqy -o=Dpkg::Use-Pty=0 install wget git
      eval "$(bash install_julia.sh 1.0)"
      git clone https://github.com/JuliaLang/Example.jl
      cd Example.jl

test:
  extends:
    - .example
    - .test

documentation:
  stage: test
  extends:
    - .example
    - .documentation
