#
# common functionality
#

# test.yml is always to be included

stages:
  - build
  - test
  - post
  - deploy

cache:
  key: julia
  paths:
    - downloads


#
# Julia versions
#

.julia:v0.7:
  before_script:
    - apt update
    - apt install -y wget
    - wget -N -P downloads/ https://julialang-s3.julialang.org/bin/linux/x64/0.7/julia-0.7.0-linux-x86_64.tar.gz
    - tar -C /usr -x -z --strip-components=1 -f downloads/julia-0.7.0-linux-x86_64.tar.gz

.julia:v1.0:
  before_script:
    - apt update
    - apt install -y wget
    - wget -N -P downloads/ https://julialang-s3.julialang.org/bin/linux/x64/1.0/julia-1.0.4-linux-x86_64.tar.gz
    - tar -C /usr -x -z --strip-components=1 -f downloads/julia-1.0.4-linux-x86_64.tar.gz

.julia:v1.1:
  before_script:
    - apt update
    - apt install -y wget
    - wget -N -P downloads/ https://julialang-s3.julialang.org/bin/linux/x64/1.1/julia-1.1.1-linux-x86_64.tar.gz
    - tar -C /usr -x -z --strip-components=1 -f downloads/julia-1.1.1-linux-x86_64.tar.gz

.julia:v1.2:
  before_script:
    - apt update
    - apt install -y wget
    - wget -N -P downloads/ https://julialang-s3.julialang.org/bin/linux/x64/1.2/julia-1.2.0-linux-x86_64.tar.gz
    - tar -C /usr -x -z --strip-components=1 -f downloads/julia-1.2.0-linux-x86_64.tar.gz

.julia:v1.3:
  before_script:
    - apt update
    - apt install -y wget
    - wget -N -P downloads/ https://julialang-s3.julialang.org/bin/linux/x64/1.3/julia-1.3.0-rc3-linux-x86_64.tar.gz
    - tar -C /usr -x -z --strip-components=1 -f downloads/julia-1.3.0-rc3-linux-x86_64.tar.gz

.julia:dev:
  before_script:
    - apt update
    - apt install -y wget
    - wget -N -P downloads/ https://julialangnightlies-s3.julialang.org/bin/linux/x64/julia-latest-linux64.tar.gz
    - tar -C /usr -x -z --strip-components=1 -f downloads/julia-latest-linux64.tar.gz

.julia:source:
  before_script:
    - apt update
    - apt install -y git build-essential libatomic1 python gfortran perl wget m4 cmake pkg-config
    - git clone https://github.com/JuliaLang/julia
    - make -C julia -j$(nproc) install JULIA_PRECOMPILE=0 $CI_BUILD_ARGS
    - ln -s $(pwd)/julia/julia /usr/local/bin/julia


#
# test functionality
#

.test:
  stage: test
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.instantiate();
                          Pkg.build();
                          Pkg.test(; coverage=true);'
  artifacts:
    when: always
    paths:
      - deps/ext.jl
      - deps/build.log
      # gitlab-runner#2620
      - src/*.cov
      - src/*/*.cov
      - src/*/*/*.cov

# supported versions

.test:v0.7:
  extends:
    - .julia:v0.7
    - .test

.test:v1.0:
  extends:
    - .julia:v1.0
    - .test

.test:v1.1:
  extends:
    - .julia:v1.1
    - .test

.test:v1.2:
  extends:
    - .julia:v1.2
    - .test

.test:v1.3:
  extends:
    - .julia:v1.3
    - .test

.test:dev:
  extends:
    - .julia:dev
    - .test

.test:source:
  extends:
    - .julia:source
    - .test
