#
# common functionality
#

# test.yml is always to be included

stages:
  - build
  - test
  - post
  - deploy

variables:
  JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"

# root job that other jobs extend
.root:
  image: "juliagpu/julia:${CI_VERSION_TAG}-${CI_IMAGE_TAG}"
  only:
    variables:
      - $CI_IMAGE_TAG
      - $CI_VERSION_TAG


#
# test functionality
#

.test:
  extends: .root
  stage: test
  before_script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - mkdir $JULIA_DEPOT_PATH # Pkg.jl#325
  script:
    - julia --project -e 'using Pkg;
                          Pkg.instantiate();
                          Pkg.build();
                          Pkg.test(; coverage=true);'
  artifacts:
    when: always
    paths:
      - Manifest.toml
      - .julia/
      - deps/ext.jl
      - deps/build.log
      # gitlab-runner#2620
      - src/*.cov
      - src/*/*.cov
      - src/*/*/*.cov

# supported versions

.test:v0.7:
  extends: .test
  variables:
    CI_VERSION_TAG: 'v0.7'

.test:v1.0:
  extends: .test
  variables:
    CI_VERSION_TAG: 'v1.0'

.test:v1.1:
  extends: .test
  variables:
    CI_VERSION_TAG: 'v1.1'

.test:v1.2:
  extends: .test
  variables:
    CI_VERSION_TAG: 'v1.2'

.test:v1.3:
  extends: .test
  variables:
    CI_VERSION_TAG: 'v1.3'

.test:dev:
  extends: .test
  variables:
    CI_VERSION_TAG: 'dev'
